### ISSUE TITLE
JSFoo 2016 - after talk Hackathon.

### ISSUE THREAD

**Issue by cherrymathew** [decant/decant#2]
**Hackathon** at **6.30pm** at the **banquet hall.**

This ticket is a placeholder for people who want to attend the after  [talk](https://jsfoo.talkfunnel.com/2016/15-decant-if-you-cant-decant-distill-it) hackathon.

The hackathon will be held today (15th Sept) in the Banquet hall after the flash talks (6.30ish)
(This may be subject to change)

Broadly speaking, one would expect to have a run-through familiarisation of the code, and get a write a simple SMS plugin.
People with more ambition, could write plugins for other applications like Telegram
People with architectural and design bent could come up with UI and other architectural ideas.
People portability interests could have a look at porting the framework to other phones.

Overall, the ambition is to hack on something on decant, and keep them going.

Happy Hacking!

Please watch (subscribe to) this ticket (issue) for further announcements.

**Comment by cherrymathew** [comment]
Hi everyone, so we'll be at the banquet hall downstairs at 6.30pm as soon as the flash talks are over.

**Comment by coder006** [comment]
Hi @cherrymathew ,

I had to leave early due to some reasons. We can still discuss the enhancements/possibilites here or in new issues.

**Comment by cherrymathew** [comment]
@coder006 hello! no worries - keep an eye on the project page, and feel free to fork/start hacking!
