### ISSUE TITLE
Create gitter.im chat room

### ISSUE THREAD

**Issue by scriptnull** [decant/decant#3]
Hi @fraggerfox and @cherrymathew ,
   First of all, good talk guys. I think, we should start by creating a gitter.im chat room for this repository. We could have brief chats on ideas based around `decant`.

Tasks: 
- [x] Sign up for https://gitter.im/ and create a chat room. ( I think , only collaborators can create chat rooms for repos. So one of you guys should do it, I guess )
- [x] Add a gitter badge to README. So that people can easily join conversations.

**Comment by fraggerfox** [comment]
I have made a gitter.im chat room which you can access at https://gitter.im/decant/decant

The gitter badge was added to the README via this pull request https://github.com/decant/decant/pull/4

Feel free to close the ticket once you have reviewed the changes.
